# Generated by Django 4.1 on 2023-01-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=100000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
