# Generated by Django 4.1 on 2023-02-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blog_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='md',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.URLField(default=''),
        ),
    ]
